# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08127592ec001b49dea7c6097b50bf486bda0534f79f4ef71d6a561596819dd1b0e081fac2d2e51381ab7f182650fea1af2957860e20aa0898047accb4dd789

test:
  secret_key_base: 2860a60acbc6cda8a1991811f185a7e755d35945b11bf75f543c8a514f158b2e8b941b159b5a0e338419e435ef49942303fcb8b07dbee794c1a0f5e1639d6073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
